############################################################################################
- name: thread
  display_name: Thread
  page: thread.html
  strapline: Helping Melbourne Business School to be leaders in digital learning.
  photoset_id: 72157627733589935
  quotes:
    - at: Thu Feb 07 11:48:28 +1100 2013
      attribution: Ben Birnbaum from Cogent said
      quote: Users are loving the new iPad app!
    - at: Fri Feb 01 11:20:28 +1100 2013
      attribution: Ben Green from Cogent said
      quote: Journal for the Thread iPad app - one place to store all your learning.

############################################################################################
- name: eventer
  display_name: Eventer
  page: eventer.html
  strapline: Changing what it&rsquo;s like to watch an event you couldn&rsquo;t make it to.
  photoset_id: 72157627873365994
  quotes:
    - at: Fri Dec 14 11:20:28 +1100 2012
      attribution: Marty Andrews from Cogent said
      quote: "Enjoyed shouting drinks to all at YOW! 2012"
    - at: Fri Dec 14 11:20:28 +1100 2012
      attribution: Amelia Crook from Cogent said
      quote: "We've been mapping out the customer landscape for Eventer."

############################################################################################
- name: readtime
  display_name: Readtime
  page: readtime.html
  strapline: Getting things read on your iPhone.<br>&nbsp;
  photoset_id: 72157630704255124
  quotes:
    - at: Fri Dec 14 09:26:54 +1100 2012
      attribution: Ben Green from Cogent said
      quote: "Plotting and scheming for the next release of Readtime."
    - at: Fri Oct 20 09:20:28 +1100 2012
      attribution: Ben Birnbaum from Cogent said
      quote: "Overnight we had a pretty extensive write up on cnet.com."

############################################################################################
- name: rea
  display_name: REA Group
  page: rea.html
  strapline: Rebuilding the Customer Platform, ground up.
  photoset_id: 72157630706064756
  archived: true
  quotes:
    - at: Fri Aug 10 11:10:28 +1100 2012
      attribution: Marty Andrews from Cogent said
      quote: We turned the lights on in production for the first 50 agents. Woot!
    - at: Thu Jul 5 14:20:28 +1100 2012
      attribution: Rob Mitchell from Cogent said
      quote: Is that pushed to the cloud?

############################################################################################
- name: tesselaar
  display_name: Tesselaar
  page: tesselaar.html
  strapline: An efficient back-office was in order for Paul Tesselaar.
  photoset_id: 72157627733596203
  quotes:
    - at: Wed Oct 5 14:20:28 +1100 2011
      attribution: Warren from Cogent said
      quote: Can&rsquo;t wait to see this working in the wild.
    - at: Fri Oct 7 14:20:28 +1100 2011
      attribution: Andy from Cogent said
      quote: Dotland and Stockland are bending my brain.


############################################################################################
# - name: the_alfred_hospital
#   display_name: The Alfred Hospital
#   page: the_alfred_hospital.html
#   strapline: A product prototype that could improve quality of treatment of many thousands of people.
#   photoset_id: 72157627749031953
#   quotes:

